
namespace Service.Models
{
    public class ScriptGenerationHistory
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
        public Service.GrpcAutoGenerated.DatabaseDialect Dialect { get; set; }
        public DateTime RequestedAt { get; set; }
    }
}
