using Service.Interfaces;
using ScriptFileBuilders.GrpcAutogenerated;

namespace Service.Models
{
    public class ScriptGeneratorFactory : IScriptGeneratorFactory
    {
        private readonly Dictionary<DatabaseDialect, IScriptGenerator> _generators;
        
        public ScriptGeneratorFactory(IEnumerable<IScriptGenerator> generators)
        {
            _generators = generators.ToDictionary(g => g.Dialect, g => g);
        }
        
        public IScriptGenerator GetGenerator(DatabaseDialect dialect)
        {
            if (_generators.TryGetValue(dialect, out var generator))
                return generator;

            throw new NotSupportedException($"Dialect {dialect} is not supported");
        }
    }
}
