using FluentValidation;
using ScriptFileBuilders.GrpcAutogenerated;

namespace Storefront.Validators
{
    public class BuildRequestValidator : AbstractValidator<BuildRequest>
    {
        public BuildRequestValidator()
        {
            RuleFor(r => r.Quantity).GreaterThan(0).LessThan(5000001).WithMessage("Max quantity is 500000");
            RuleFor(r => r.Dialect).IsInEnum();
        }
    }
}
