using FluentValidation;
using GenerationService.GrpcAutogenerated;

namespace Storefront.Validators
{
    public class HistoryQueryParametersValidator : AbstractValidator<HistoryQueryParameters>
    {
        public HistoryQueryParametersValidator()
        {
            //Pagination
            RuleFor(p => p.PaginationParameters.PageNumber).GreaterThan(0);
            RuleFor(p => p.PaginationParameters.PageNumber).LessThanOrEqualTo(100);
            RuleFor(p => p.PaginationParameters.PageSize).GreaterThan(0);
            RuleFor(p => p.PaginationParameters.PageSize).LessThanOrEqualTo(20);

            //Dates
            RuleFor(p => p.FilterParameters.DateTo).Must((parameters, dateTo) => dateTo >= parameters.FilterParameters.DateFrom)
                .When(p => p.FilterParameters.DateTo != null && p.FilterParameters.DateFrom != null && p.FilterParameters.ExactDate == null);
            RuleFor(f => f.FilterParameters.DateTo).Must(dateTo => dateTo == null)
                .When(parameters => parameters.FilterParameters.ExactDate != null);
            RuleFor(f => f.FilterParameters.DateFrom).Must(dateFrom => dateFrom == null)
                .When(parameters => parameters.FilterParameters.ExactDate != null);
        }
    }
}
