using FluentValidation;
using Storefront.GrpcAutoGenerated;

namespace Storefront.Validators
{
    public class HistoryQueryParametersValidator : AbstractValidator<HistoryQueryParameters>
    {
        public HistoryQueryParametersValidator()
        {

            RuleFor(p => p.PaginationParameters.PageNumber).GreaterThan(0);
            RuleFor(p => p.PaginationParameters.PageNumber).LessThanOrEqualTo(100);
            RuleFor(p => p.PaginationParameters.PageSize).GreaterThan(0);
            RuleFor(p => p.PaginationParameters.PageSize).LessThanOrEqualTo(20);
            RuleFor(p => p.DateTo).Must((parameters, dateTo) => dateTo >= parameters.DateFrom).When(p => p.DateTo != null && p.DateFrom != null);    
        }
    }
}
