using ScriptFileBuilders.GrpcAutogenerated;

namespace Storefront.Models
{
    public class ScriptGenerationHistory
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
        public DatabaseDialect Dialect { get; set; }
        public DateTime RequestedAt { get; set; }
    }
}
