using GenerationService.GrpcAutogenerated;
using Storefront.Models;
using Google.Protobuf.WellKnownTypes;

namespace Storefront.Clients
{
    public class ScriptGenerationHistoriesClient
    {
        private readonly ScriptGenerationHistoriesServiceProto.ScriptGenerationHistoriesServiceProtoClient _client;
        public ScriptGenerationHistoriesClient(ScriptGenerationHistoriesServiceProto.ScriptGenerationHistoriesServiceProtoClient client)
        {
            _client = client;
        }
        public async ValueTask<PagedResult<ScriptGenerationHistory>> GetAsync(HistoryQueryParameters parameters, CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();
            
            var response = await _client.GetAsync(parameters);
            
            var histories = response.Histories
                .Select(h => new ScriptGenerationHistory()
                {
                    Id = h.Id,
                    Quantity = h.Quantity,
                    Dialect = h.Dialect,
                    RequestedAt = h.RequestedAt.ToDateTime()
                })
                .ToList();

            return new PagedResult<ScriptGenerationHistory>()
            {
                Items = histories,
                TotalCount = response.TotalCount
            };
        }
        public async ValueTask DeleteAsync(CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();
            
            await _client.DeleteAsync(new Empty());
        }

        public async ValueTask RemoveHistoryByIdAsync(int id, CancellationToken cancellationToken)
        {
            await _client.RemoveAsync(new RemoveHistoryRequest()
            {
                Id = id
            });
        }
    }
}
