using Grpc.Core;
using ScriptFileBuilders.GrpcAutogenerated;
using System.Text;

namespace Storefront.Clients
{
    public class ScriptGenerationServiceClient
    {
        private readonly ScriptFileBuilder.ScriptFileBuilderClient _client;

        public ScriptGenerationServiceClient(ScriptFileBuilder.ScriptFileBuilderClient client)
        {
            _client = client;
        }
        public async IAsyncEnumerable<byte[]> BuildAsync(BuildRequest request, CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var response = _client.Build(request, deadline: DateTime.UtcNow + TimeSpan.FromMinutes(5));

            await foreach (var stringValue in response.ResponseStream.ReadAllAsync(cancellationToken))
            {
                yield return Encoding.UTF8.GetBytes(stringValue.Value);
            }
        }
    }
}
