using Storefront.GrpcAutoGenerated;
using Storefront.Models;
using Google.Protobuf.WellKnownTypes;

namespace Storefront.Clients
{
    public class ScriptGenerationHistoriesClient
    {
        private readonly ScriptGenerationHistoriesService.ScriptGenerationHistoriesServiceClient _client;
        public ScriptGenerationHistoriesClient(ScriptGenerationHistoriesService.ScriptGenerationHistoriesServiceClient client)
        {
            _client = client;
        }
        public async Task<List<ScriptGenerationHistory>> GetAsync(HistoryQueryParameters parameters)
        {
            var response = await _client.GetAsync(parameters);
            var histories = response.Histories
                .Select(h => new ScriptGenerationHistory()
                {
                    Quantity = h.Quantity,
                    Dialect = h.Dialect,
                    RequestedAt = h.RequestedAt.ToDateTime()
                })
                .ToList();

            return histories;
        }
        public async Task DeleteAsync()
        {
            await _client.DeleteAsync(new Empty());
        }
    }
}
