using ScriptFileBuilders.GrpcAutogenerated;

namespace Service.Interfaces
{
    public interface IScriptGenerator
    {
        DatabaseDialect Dialect { get; }
        IAsyncEnumerable<string> GenerateAsync(int quantity, CancellationToken cancellationToken);
    }
}