using Bogus;
using Service.Interfaces;
using Service.Models;
using System.Text;
using ScriptFileBuilders.GrpcAutogenerated;

namespace Service.Services
{
    public class PostgresScriptGenerator : IScriptGenerator
    {
        public DatabaseDialect Dialect => DatabaseDialect.Postgresql;
        public async IAsyncEnumerable<string> GenerateAsync(int quantity, CancellationToken cancellationToken)
        {
            var script = new StringBuilder();
            var faker = new Faker<MockUser>();
            faker.RuleFor(u => u.Firstname, f => f.Name.FirstName())
                 .RuleFor(u => u.Lastname, f => f.Name.LastName())
                 .RuleFor(u => u.Email, f => f.Internet.Email())
                 .RuleFor(u => u.Password, f => f.Internet.Password())
                 .RuleFor(u => u.BirthDate, f => f.Person.DateOfBirth)
                 .RuleFor(u => u.PhoneNumber, f => f.Phone.PhoneNumberFormat());

            script.AppendLine(@"
                CREATE TABLE IF NOT EXISTS FakeUsers(
                    Id SERIAL PRIMARY KEY, 
                    Firstname VARCHAR(255), 
                    Lastname VARCHAR(255), 
                    Email VARCHAR(255), 
                    PasswordHash VARCHAR(255), 
                    BirthDate TIMESTAMP, 
                    PhoneNumber VARCHAR(12));
                INSERT INTO FakeUsers(Firstname, Lastname, Email, PasswordHash, BirthDate, PhoneNumber) VALUES");

            for (int i = 0; i < quantity; i++)
            {
                cancellationToken.ThrowIfCancellationRequested();
                
                var user = faker.Generate();
                string birthDate = user.BirthDate.ToString("yyyy-MM-dd");
                string firstName = user.Firstname.Replace('\'', ' ');
                string lastName = user.Lastname.Replace('\'', ' ');

                script.Append($"(" +
                    $"'{firstName}', " +
                    $"'{lastName}', " +
                    $"'{user.Email}', " +
                    $"'{user.Password}', " +
                    $"'{birthDate}', " +
                    $"'{user.PhoneNumber}')");

                if (i != quantity - 1)
                    script.Append(',');

                yield return script.ToString();
                script.Clear();
            }

            script.Append(";");

            yield return script.ToString();
        }
    }
}
