using Google.Protobuf.WellKnownTypes;
using Grpc.Core;
using GenerationService.GrpcAutogenerated;
using GenerationsData.GrpcAutogenerated;

namespace Service.Services
{
    public class ScriptGenerationHistoriesService : ScriptGenerationHistoriesServiceProto.ScriptGenerationHistoriesServiceProtoBase//REPOSITORY
    {
        private readonly ScriptGenerationHistoryRepository.ScriptGenerationHistoryRepositoryClient _client;
        public ScriptGenerationHistoriesService(ScriptGenerationHistoryRepository.ScriptGenerationHistoryRepositoryClient client)
        {
            _client = client;
        }
        public override async Task<ScriptGenerationHistoriesResponse> Get(HistoryQueryParameters request, ServerCallContext context)
        {
            var response = await _client.GetAsync(request);

            context.CancellationToken.ThrowIfCancellationRequested();
            
            return response;
        }
        public override async Task<Empty> Add(AddScriptGenerationHistoryRequest request, ServerCallContext context)
        {
            await _client.AddAsync(request);

            return new Empty();
        }
        public override async Task<Empty> Delete(Empty request, ServerCallContext context)
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            
            return await _client.DeleteAsync(request);
        }

        public override async Task<Empty> Remove(RemoveHistoryRequest request, ServerCallContext context)
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            return await _client.RemoveAsync(request);
        }
    }
}