using Service.GrpcAutoGenerated;
using Google.Protobuf.WellKnownTypes;
using Grpc.Core;

namespace Service.Services
{
    public class ScriptGenerationHistoriesServiceImpl : ScriptGenerationHistoriesService.ScriptGenerationHistoriesServiceBase
    {
        private readonly ScriptGenerationHistoryRepository.ScriptGenerationHistoryRepositoryClient _client;
        public ScriptGenerationHistoriesServiceImpl(ScriptGenerationHistoryRepository.ScriptGenerationHistoryRepositoryClient client)
        {
            _client = client;
        }
        public override async Task<ScriptGenerationHistoriesResponse> Get(HistoryQueryParameters request, ServerCallContext context)
        {
            var response = await _client.GetAsync(request);

            return response;
        }
        public override async Task<Empty> Add(AddScriptGenerationHistoryRequest request, ServerCallContext context)
        {
            await _client.AddAsync(request);

            return new Empty();
        }
        public override async Task<Empty> Delete(Empty request, ServerCallContext context)
        {
            var response = await _client.DeleteAsync(request);

            return response;
        }
    }
}